site_name: SpeedSync_CAN_OBD
site_author: Jungledede
site_url: ""
use_directory_urls: false

theme:
  name: material
  locale: en
  #logo:
  #favicon:
  features:
    - navigation.instant
    - navigation.sections
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  extra:
    copyright: Author is Jungledede. Under MIT licence. Please source the git project if reuse.

markdown_extensions:
  - admonition
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.highlight:
      auto_title: true
      use_pygments: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - smarty
  - tables
  - toc:
      permalink: true

